disable_all_formatting = false
indent_style = "Block"
reorder_imports = true
use_small_heuristics = "Max"
binop_separator = "Front"
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
#fn_args_density = "Tall"
fn_single_line = true
imports_layout = "HorizontalVertical"
merge_imports = true
max_width = 80
force_multiline_blocks = true
normalize_comments = true
remove_nested_parens = true
reorder_modules = true
reorder_impl_items = true
where_single_line = false
hard_tabs = false
imports_indent = "Block"
match_block_trailing_comma = true
skip_children = false
space_before_colon = false
space_after_colon = true
struct_lit_single_line = false
tab_spaces = 4
trailing_semicolon = false
type_punctuation_density = "Wide"
use_field_init_shorthand = false
use_try_shorthand = false
wrap_comments = true
match_arm_blocks = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
